import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [data, setData] = useState("");

  useEffect(() => {
    callBackend();
  }, []); // Empty dependency array to run the effect only once on component mount

  function callBackend() {
    fetch("https://backend.argouniverse.com/")
      .then((response) => response.json())
      .then((data) => {
        console.log(data);
        // Handle the retrieved data
        setData(data);
      })
      .catch((error) => {
        // Handle any errors
        console.log("Error:", error);
      });
  }

  return (
    <>
      <Head>
        <title>Argo Universe Frontend App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <center>
          <a
            target="_blank"
            href="https://github.com/argo-universe"
          >
            <Image
              style={{ margin: "100px" }}
              src="/argo-universe.png"
              alt="Next.js Logo"
              width={550}
              height={255}
              priority
            />
          </a>
          <div className={styles.description}>
            <p style={{ padding: "10px", margin: "30px 0px" }}>{data.quote}</p>
            <p>
              <a
                target="_blank"
                href="https://github.com/argo-universe/backend-app"
              >
                https://github.com/argo-universe/backend-app
              </a>
            </p>
            <div></div>
          </div>
          <button
            style={{ padding: "10px", margin: "10px" }}
            onClick={callBackend}
          >
            Get Another
          </button>
        </center>

        <div className={styles.center}></div>
        <p></p>
      </main>
    </>
  );
}
