import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            this text was fetched from backend api &nbsp;
            <code className={styles.code}>https://github.com/argo-universe/backend-app</code>
          </p>
          <div>
          
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/argo-universe.png"
            alt="Next.js Logo"
            width={550}
            height={255}
            priority
          />
        </div>
        <p></p>

 
      </main>
    </>
  )
}
